services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgressecret
      POSTGRES_DB: postgres
    expose:
    - "5432"
    volumes:
    - ./data:/var/lib/postgresql/data
  backend:
    build: .
    environment:
      DB_DATABASE: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgressecret
      DB_PORT: 5432
      DB_HOST: postgres
      CORS_ORIGIN: http://localhost:5173
    ports:
    - "3000:3000"